### PR TITLE
Phar distribution

### PR DESCRIPTION
**Pull request by killerwolf**
Here is how to compile 
- download box.phar from https://github.com/box-project/box2/releases
- run composer install without dev deps `composer install --no-dev`
- build the phar distribution with `php box.phar build`

The Phar distribution is <1M

``` shell
killerbookpro:karma killerwolf$ ls -alh|grep karma.phar
-rw-r--r--   1 killerwolf  staff   913K Oct 23 00:03 karma.phar
killerbookpro:karma killerwolf$ php karma.phar -V
Karma version 5.3.0
```

Enjoy

TODOs:
- Automate phar dist within build.xml and trigger it with travis
- Mimic composer `--version` command, which returns 'the tag, short-hash and build time'
- Release these phars under github/release page (and/or even bintray)
- Find a way to test the phar distribution (within travis maybe)
- ...

### CODE REVIEW

**Comment by Niktux** [comment]
Thanks a lot !

Currently in holidays preparing my move, I will check this when I'll be back (in early november)

**Comment by killerwolf** [comment]
Ok, no prob

**Comment by killerwolf** [comment]
up

**Comment by killerwolf** [comment]
We can leverage the `deployment` feature of travis, to push successfull tagged commits build to github/releases
https://docs.travis-ci.com/user/deployment/releases/

**Comment by Niktux** [comment]
I'm trying to play with it this week :smile:

**Comment by Niktux** [comment]
See PR#99

**Pull request closed without merging**
